### PR TITLE
flash/nor/spi: add zetta zd25q16

### PR DESCRIPTION
**Pull request by picmaster**
* Zetta 16 Mbit (2 MiB) SPI flash
* Tested on Olimex RP2040-PICO30 and Neo6502 boards

### CODE REVIEW

**Comment by lurch** [comment]
I wonder if this should be submitted to the upstream openocd, rather than our downstream fork? :thinking:

**Comment by picmaster** [comment]
Yes, I've already submitted the patch to the upstream, but looking at the time it took to progress from 0.11.0 to 0.12.0 I decided to submit it also here, so we can use in the meantime.

**Comment by P33M** [comment]
If there's a shipping RP2040 board with this flash chip on, and a corresponding board define in the Pico SDK, then I would be inclined to merge the patch downstream. Is this the case?

**Comment by picmaster** [comment]
Exactly, there already exist real products with this flash chip (as listed in the patch):
- RP2040-PICO30 (https://www.olimex.com/Products/MicroPython/RP2040-PICO30/open-source-hardware)
- Neo6502 (https://www.olimex.com/Products/Retro-Computers/Neo6502/open-source-hardware)

I haven't added board definitions in the SDK, because the SDK is perfectly usable the way it is.

**Pull request merged**
