### PR TITLE
Fixup some compiler warnings (therefor errors) that appear with gcc 11.1

### PR DESCRIPTION
**Pull request by JamesH65**

### CODE REVIEW

**Comment by lurch** [comment]
Looks like `rp2040` is now the default branch in this repo? (and is also the branch that https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf references)

**Comment by JamesH65** [comment]
I just used the branch that is used when you download openocd via pico_setup.sh ....

**Comment by aallan** [comment]
> I just used the branch that is used when you download openocd via pico_setup.sh ....

Honestly not entirely sure how correct pico_setup.sh is anymore. I know the documentation was updated by @liamfraser (I think?) after the branches got merged.

**Comment by liamfraser** [comment]
rp2040 and picoprobe should be indentical, but you are right. It should go into rp2040. I'll update pico setup now to point at rp2040

**Comment by aallan** [comment]
Thanks Liam!

**Comment by JamesH65** [comment]
Just changed the base branch.

**Comment by lurch** [comment]
Do you need to rebase? It says "Commits: 7" up at the top now.

**Comment by JamesH65** [comment]
Not entirely sure, but no conflicts reported with the base branch, so should be OK?

**Comment by liamfraser** [comment]
@JamesH65 there is an identical upstream commit for your change, so I am inclined to test it and pick that, just so the history will merge better in the future.

**Comment by liamfraser** [comment]
Closing in favour of #51

**Pull request closed without merging**
